org: yangzhi
app: aws-python-scheduled-cron
service: aws-python-scheduled-cron

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:ap-southeast-1:918183059025:table/CBREDG_Weekly_Security_Message"
  region: ap-southeast-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    CHAT_ID: ${env:CHAT_ID}

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every Monday at 10AM GMT+8
      - schedule: cron(00 02 ? * MON *)
  
plugins:
  - serverless-python-requirements
